## Estimating Optimal Regime from a Classification Perspective

In this section, we introduce a more general framework for estimating optimal treatment regime. This original problem of the optimal regime is reformed as a weighted classification problem which is to minimizes the expected weighted misclassification error. This method treats the two main steps, estimating the mean outcome under a regime and the following optimizing for identifying the regime, disjointedly. This lets one use any existing methods to estimate the mean outcome, such as the outcome regression, inverse probability weighted estimator (IPWE), augmented inverse probability estimator (AIPWE), etc. Moreover, any approach for weighted classification can be used with no modification to find the optimal regime. 

We consider the same setting as previous. In a single-stage clinical trial or observational study, we have $n$ subjects sampled from the patient population of interests. The treatment $A$ has options $\{ 0, 1\}$ (or $\{ -1, 1\}$).The patient characteristics vector collected before the treatment assignment is denoted by $X$, where $X\in \mathbf{R}^p$. $Y$ denotes the observed outcome of interest, and is preferred to be higher value. Then, the observed data, written as $(Y_i, A_i, X_i)$, $i = 1, \cdots, n$, are independent and identically distributed across i. The two potential outcomes are denoted by $\{ Y^*_{A=0}, Y^*_{A=1}\}$. The treatment regime is a function $d$ that maps the domain of $X$ to $\{0, 1\}$ (or $\{-1, 1\}$). We define the potential outcome under an arbitrary regime $d$ as $Y^*_d = Y^*_{A=1} d(X) + Y^*_{A=0}\left\{ 1 - d(X) \right\}$.

Under the three necessary assumptions mentioned before [ADD LINKS TO THE ASSUMPTIONS HERE], we have that $Q(X,a) \triangleq E\left(Y \mid X=X, A=a\right) = E\{ Y^{*}_{A=a} \mid X=X\}$ , for $a \in \{0, 1 \}$ ( or $\{-1, 1 \}$). 

Here we describe the classification framework for finding optimal regimes without detailed mathematical derivation.  Let $d(X)$ denote the function for an arbitrary regime. Let $C(X)$ denote the contrast function where $C(X) = E(Y \mid A=1, X) - E(Y \mid A=0, X)$.   The original estimating optimal regime problem is formalized as find the regime $d^{opt} \in \mathcal{G}$  that maximize the expected potential outcome if all the population of interest is treated following that regime:
$$d^{opt}  =\text{argmax}_{d\in \mathcal{D}} E\{ Y^*_d\}$$After some algerbra, we can show that Problem 1 is equivalent to

$$d^{opt} = \text{argmax}_{d \in \mathcal{D}} E\left\{d(X) C(X) \right\} = \text{argmin}_{d \in \mathcal{D}} E\left\{ |C(X)| \left[ \mathbf{I} \{ C(X) > 0\} - d(X) \right]^2 \right\}.$$
To consider this from the classification point of view, we consider each subject belonging to one of the two classes, 0 or 1, defined by $Z = \mathbf{I}\{ C(X) > 0\}$ . The subjects with $Z=1$  is the class of patients who benefit more from treatment 1 than treatment 0; The subjects with $Z=0$ are otherwise.   The weight that counting the loss  of misclassification for each subject is $W = |C(X)|$. 

As the contrast function $C(X)$ is usually unknown, we estimate it based on observed data by an suitable  estimator $\widehat{C}(X)$. This estimator can be obtained from the methods, such as outcome regression method, IPWE and AIPWE, by subtracting the estimator of $\widehat{E}(Y \mid A= 1, X)$ by $\widehat{E}(Y \mid A = 0, X)$. We will give the forms of $\widehat{C}(X)$  using these methods later. Naturally, we have an estimator for $\mathbf{I}\{C(X) > 0\}$ as $\mathbf{I}\{\widehat{C}(X) > 0 \}$ . Using  i.i.d n-sized sample data, we have the estimator for classes $\widehat{Z}_i = \mathbf{I}\{ \widehat{C}(X_i) > 0\}$   , and the estimator for weights $\widehat{W}_i = |\widehat{C}_i(X)|$.. Therefore, $d^{opt}$ can be estimated by 
$$\widehat{d}^{opt} = \text{argmin}_{d \in \mathcal{D}} \sum_{i=1}^{n} \left[\widehat{W}_i \{ \widehat{Z}_i - d(X_i)\}^2\right]$$As we have the estimators, we can use any weighted classifier without modification here to solve the optimal regime problem.
