## Causal Effect (Cont'd)
To summarize what we have learned about the causal effect from Rufus' family example, we emphasize the three important concepts mentioned.

> **Potential outcomes**:
Potential outcomes are defined as an individual's response if he or she is assigned to a particular level of treatment, $A=a$. Potential outcomes are also called counterfactual random variables because we can only assign one level of treatment to the individual and thus only observe one of them. All of the other potential outcomes under different levels of treatment for that individual are missing.

> **Individual causal effect**: 
Considering a binary treatment with $A=a_1$ or $a_2$, the difference between the potential outcome under treatment level $A=a_2$ and treatment level $A=a_1$, $Y^{\mbox{*}}(A=a_2) - Y^{\mbox{*}}(A=a_1)$, is defined as the individual causal effect. As we only get to observe one of the potential outcomes, the individual causal effect is not estimable.


> **Average causal effect**: 
Considering a binary treatment with $A=0$ or $1$, the average of individual causal effect  $E\{ Y^{\mbox{*}}(A=1) - Y^{\mbox{*}}(A=0)\}$, is defined as the average causal effect of the population of interest. It equals to the difference between the population-level average potential outcome under treatment level $A=1$ and under treatment level $A=0$.
