## bimDataOne
We will use the same dataset "bmiDataOne" for all the one-stage DynTxRegime methods for estimating optimal treatment regime. This dataset is excerpted from the bmiData in the DynTxRegime package to mimic a single-stage SMART of body mass index (BMI) reduction with two treatment options at the decision point. The full dataset bmiData was generated based on a clinical trial studying the effect of meal replacements on weight loss and BMI reduction in obese adolescents; see Berkowitz et al. (2010) for a complete description of the original randomized trial. 

In the dataset bmiDataOne, the baseline covariates include the following information of the patient: gender (gender), race (race), his/er parent's BMI (parentBMI), baseline BMI(baselineBMI). Each patient's treatment at the decision point (A1) is included. The treatment was randomized to meal replacement (MR) or conventional diet (CD) at the single stage with probability 0.5.  His/er BMI collected after 4-month treatment (month4BMI) is also included. This generated dataset is complete, as we implement the method after missing data have been imputed appropriately.