#### Point Exposure Studies  


In a point exposure study, we explore how a variable of interest is affected by an action taken at a single time point. In terms of clinical studies, the action is a treatment (an exposure, or an intervention). For example, in a study of weight-loss, "follow a specific exercise plan" is a treatment, as is "do not follow a specific exercise plan." The variable of interest might be BMI (Body Mass Index) or blood pressure.

##### Randomized Studies  
Randomized studies are accepted as a golden standard for examining causal treatment effect. <span style="color:red">We will give the specific definition of causal treatment effect later. In brief, ???</span> . In randomized studies, patients are assigned to different levels of treatment based on a specified randomization mechanism, such as flipping a coin for each patient. For example, we can assign a patient to follow meal plan A if the coin flip results in a head, and to meal plan B if the coin flip results in a tail. An experiment carried out by this type of randomized mechanism is called a **marginally randomized study**. Because treatment is assigned as random, the patient populations across each of the treatment categories are similar on average. Therefore, any difference in response between the two randomized groups is due to the different treatment levels.

In some cases, we might be interested in the treatment causal effect <span style="color:red">(WE'VE STILL NOT DEFINED THIS)</span> within subgroups. For example, we want to see if the exercise plan works for the female subgroup and/or the male subgroup. That is, we want to exam the stratum-specific causal effects. To do so, we flip a coin, say coin F, to randomly assign all the females to the two treatment levels; and, we use a different coin, say coin M, to randomly assign all of the males to the two treatment levels. This kind of experiment is called **conditionally randomized experiments**, which can be considered as a combination of two separate marginally randomized studies. Then, we can calculate the causal effect in the female subgroup, and the causal effect in the male subgroup. This method is called stratification. With some assumptions, the data from this kind of study can also be used to calculate the overall causal effect for the whole patient group.

##### Observational studies
In some cases, randomized studies might not be logistically practical or may even violate ethical standards. In these instances, we use observational studies. Unfortunately, in observational studies, the patient characteristics and treatment assignments are not under the control of the investigators. Due to the lack of a randomized mechanism for treatment assignment, it is hard to control confounding phenomena. As a result, some researchers are not confident in causal inferences drawn from observational studies.  Nevertheless, in the 1970's, Rubin <span style="color:red"> (NEED A CITATION) </span>extended the causal inference framework from randomized studies to observational studies, with some assumptions. 

#### Notation

Throughout this tutorial, we will use the following nomenclature and notation. Treatment variables are characterized by the fact that their values are set by the decision-maker, typically a clinician. We shall refer to the treatment variable as $A$. It can be either discrete or continuous. For example, it can be whether or not to put on sun screen, or the dosage of aspirin to take. For simplicity, we only consider the case where $A$ is a binary treatment with two possible values, e.g. $\{-1,1\}$ or $\{0, 1\}$.  Covariates are variables, such as age, that cannot be set by the decision-maker and are not affected by treatment. (IF YOU DON'T USE THE NEW VERBIAGE CHANGE THE COVARIATE TO SOMETHING LIKE AGE.) We use $\boldsymbol{X}$ to denote a subject covariate collected before treatment assignment, i.e., baseline characteristics. What characteristics should be included in $\boldsymbol{X}$ is decided by experts in the field. Responses, denoted as $Y$, are variables that cannot be set by the decision-maker, but the value of which can be affected by treatment, e.g., BMI. We can summarize the data available for the i-th individual as 
$$(Y_i, A_i, \boldsymbol{X}_i), i = 1, 2, \dots, n,$$
where $n$ denotes the number of subjects in the study. To keep consistent with the convention of the field, we will use capital letters to denote variables, and lower-case letters to denote the values of variables. 


