## Point Exposure Studies  

We briefly introduce point exposure studies from which we can estimate the average causal effect. In a point exposure study, we explore how a variable of interest is affected by an action taken at a single time point. In terms of clinical studies, the action is a treatment (an exposure, or an intervention). For example, in a study of weight-loss, "follow a specific exercise plan" is a treatment, as is "do not follow a specific exercise plan." The variable of interest might be BMI (Body Mass Index).

#### Randomized Studies  
Randomized studies are accepted as a golden standard for examining causal treatment effect. In randomized studies, patients are assigned to different levels of treatment based on a specified randomization mechanism, such as flipping a coin for each patient. For example, we can assign a patient to following the exercise plan if the coin flip results in a head, and not following the plan if the coin flip results in a tail. An experiment carried out by this type of randomized mechanism is called a **marginally randomized study**. Because treatment is assigned as random, the patient populations across each of the treatment categories are similar on average. Therefore, any difference in response between the two randomized groups is due to the different treatment levels.

In some cases, we might be interested in the treatment causal effect within subgroups. For example, we want to see if the exercise plan works for the female subgroup and/or the male subgroup. That is, we want to exam the stratum-specific causal effects. To do so, we flip a coin, say coin F, to randomly assign all the females to the two treatment levels; and, we use a different coin, say coin M, to randomly assign all of the males to the two treatment levels. This kind of experiment is called **conditionally randomized experiments**, which can be considered as a combination of two separate marginally randomized studies, one for females and one for males. Then, we can calculate the causal effect in the female subgroup, and the causal effect in the male subgroup. This method is called stratification. With some assumptions, the data from this kind of study can also be used to calculate the overall causal effect for the whole patient group.
