## Three Necessary Assumptions (Cont'd)
Equipped with the three key assumptions above, we can now use observed data $(\boldsymbol{X}, A, Y)$ to infer the distribution of $(\boldsymbol{X}, Y^*_{A=0}, Y^*_{A=1})$.

Under these assumptions, we can prove that, 
$$E\left(Y^*_{A=a} \right) = E( Y \mid A=a ) \text{, for } a = 0, 1.$$
This means that the conditional mean of the observed outcome $Y$ given treatment assignment $A=a$ is equal to the average of the potential outcome under treatment assignment $A=a$.

Therefore, we have that 
$$E\left( Y^*_{A=1} \right) - E\left( Y^*_{A=0} \right) = E( Y \mid A=1 ) - E( Y \mid A=0 ).$$
That is the average observed treatment difference is equal to the average causal treatment effect under these assumptions.

For experiments with stratification, we have that
$$E\left( Y^{*}_{A=a} \mid \boldsymbol{X}=\boldsymbol{x}\right) = E\left( Y \mid \boldsymbol{X}=\boldsymbol{x}, A=a\right)\text{, for } a=0,1.$$
That is the conditional expectation of the potential outcome under treatment $A=a$, $Y^{*}_{A=a}$, given the covariate $\boldsymbol{X}=\boldsymbol{x}$ equals to the conditional expectation of the observed response give the covariate $\boldsymbol{X}=\boldsymbol{x}$ and the treatment $A=a$.

Then, we can calculate the stratum-specific causal treatment effect for patients with the same covariate $\boldsymbol{X} =\boldsymbol{x}$ as
$$E\left( Y^{*}_{A=1} \mid \boldsymbol{X}=\boldsymbol{x}\right) - E\left( Y^{*}_{A=0} \mid \boldsymbol{X}=\boldsymbol{x}\right) = E\left( Y \mid \boldsymbol{X}=\boldsymbol{x}, A=1\right) - E\left( Y \mid \boldsymbol{X}=\boldsymbol{x}, A=0\right).$$

Moreover, the overall average causal treatment effect is calculated as
$$E\left( Y^*_{A=1} \right) - E\left( Y^*_{A=0} \right) = E \left(E\left( Y^{*}_{A=1} \mid \boldsymbol{X}=\boldsymbol{x}\right)\right) - E \left(E\left( Y^{*}_{A=0} \mid \boldsymbol{X}=\boldsymbol{x}\right)\right) = E\left(E\left( Y \mid \boldsymbol{X}=\boldsymbol{x}, A=1\right)\right) - E\left(E\left( Y \mid \boldsymbol{X}=\boldsymbol{x}, A=0\right)\right).$$

