## Notation

Throughout this tutorial, we will use the following nomenclature and notation. Treatment variables are characterized by the fact that their values are set by the decision-maker, typically a clinician. We shall refer to the treatment variable as $A$. It can be either discrete or continuous. For example, it can be whether or not to put on sun screen, or the dosage of aspirin to take. For simplicity, we only consider the case where $A$ is a binary treatment with two possible values, e.g. $\{0, 1\}$ or $\{-1,1\}$.  Covariates are variables, such as age, that cannot be set by the decision-maker and are not affected by treatment. We use $\boldsymbol{X}$ to denote a set of subject covariates collected before treatment assignment, i.e., baseline characteristics. What characteristics should be included in $\boldsymbol{X}$ is decided by experts in the field. Responses, denoted as $Y$, are variables that cannot be set by the decision-maker, but the value of which can be affected by treatment, e.g., BMI. We can summarize the data available for the i-th individual as 
$$(\boldsymbol{X}_i, A_i, Y_i), i = 1, 2, \dots, n,$$
where $n$ denotes the number of subjects in the study. To keep consistent with the convention of the field, we will use capital letters to denote variables, and lower-case letters to denote the values of variables. 
