## Stable Unit Treatment Value Assumption

Examining the two tables above, you might notice that we are already making some assumption. Take Rufus for instance. His treatment level is $A=1$, and his observed BMI value is Y = 24, which equals to his potential outcome under treatment $A=1$, $Y^{*}_{A =1}=24$. Same applies to the others in the table. This leads to the first assumption we are going to introduce, which is called the Stable Unit Treatment Value Assumption.

**Stable Unit Treatment Value Assumption (SUTVA or the consistency assumption)**: 
the actual observed response, $Y$, for an individual who received treatment level $A=a$ is equal to the potential outcome for the individual with that assigned treatment, $Y^{*}_{A=a}$. Formally, we have $$Y = Y^{*}_{A =1}{\mathbf{I}}(A = 1) + Y^{*}_{A =0}{\mathbf{I}}(A = 0)$$

This not only implies that we have perfect measurement, but also infers that there are no interference between subjects. For instance, Jessy, Rufus' sister,starts a vegetarian diet, but her action does not influence Rufus' life style. More precisely, Rufus' outcome is not influenced by his sister and any other family members. However, when it comes to contagious diseases, a subject's interaction with the others in the population often affects the his or her outcome. This assumption of no interference between subjects was introduced by Cox, and was later included in SUTVA by Rubin.


